### ISSUE TITLE
Improve handling of failed chat connections

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#10]
Should we improve the handling of chat connections that failed to join?

**Comment by JoshuaSkelly** [comment]
I would ask can we? Does the IRC server actually return any message, or does it fail silently? I'm conerned that it is the latter.

Can you get a message log of the interaction you are talk about?

**Comment by PythooonUser** [comment]
Sure thing (and yes, it fails silently).

## Test Script
So that is my test script:
```python
import time
from twitchobserver import Observer, ChatEvent

observer = Observer("pythooonuser", "oauth:abcdefghijklmnopqrstuvwxyz0123", "pythooonuser")

def print_event(event):
    print("EVENT\n", event.dumps(), sep="")

observer.subscribe(print_event)

observer.start()
time.sleep(20)
observer.stop()
```
Additionally I added:
```
print("RESPONSE\n:", response, sep="")
```
to the two occurences of `self._socket.recv()` where we receive input.

## Correct Join
When I correctly join my channel, the output reads:
```
PS D:\Projects\twitch-observer> python .\test.py
RESPONSE
:tmi.twitch.tv 001 pythooonuser :Welcome, GLHF!
:tmi.twitch.tv 002 pythooonuser :Your host is tmi.twitch.tv
:tmi.twitch.tv 003 pythooonuser :This server is rather new
:tmi.twitch.tv 004 pythooonuser :-
:tmi.twitch.tv 375 pythooonuser :-
:tmi.twitch.tv 372 pythooonuser :You are in a maze of twisty passages, all alike.
:tmi.twitch.tv 376 pythooonuser :>

RESPONSE
::pythooonuser!pythooonuser@pythooonuser.tmi.twitch.tv JOIN #pythooonuser

EVENT
JOIN #pythooonuser

RESPONSE
::pythooonuser.tmi.twitch.tv 353 pythooonuser = #pythooonuser :pythooonuser
:pythooonuser.tmi.twitch.tv 366 pythooonuser #pythooonuser :End of /NAMES list
```

## Incorrect Join
Now I change the channel name to a non-existing one: `pythooonuser_1234`.
```
PS D:\Projects\twitch-observer> python .\test.py
RESPONSE
:tmi.twitch.tv 001 pythooonuser :Welcome, GLHF!
:tmi.twitch.tv 002 pythooonuser :Your host is tmi.twitch.tv
:tmi.twitch.tv 003 pythooonuser :This server is rather new
:tmi.twitch.tv 004 pythooonuser :-
:tmi.twitch.tv 375 pythooonuser :-
:tmi.twitch.tv 372 pythooonuser :You are in a maze of twisty passages, all alike.
:tmi.twitch.tv 376 pythooonuser :>
```
So what we actually could do, is waiting for the token `End of /NAMES list` which returned all currently available chatters in the chat (if the number is not higher than 1000).
This would indicate that we have a successful join - maybe.

**Comment by PythooonUser** [comment]
Since we can connect to multiple chats at a time, I propose to remove the `_channel` attribute from the observer since it is not unique and can have multiple values at a given time.

Maybe we could change this in something like, `channels_pending_to_connect_with` and `channels_pending_to_unconnect_with`.

Or we use a list instead and keep the attribute to keep a reference to all currently active chat connections.

However in the inbound worker thread we could check e.g. for `:nickname.tmi.twitch.tv 366 nickname #channel :End of /NAMES list` and insert all pending channel names.

It remains to define after which period of time a join or part proceeding is declared unsuccessful.

BUT ... I'm not sure about this. Seems to be not worth the effort.

Because when a message failed to be send to a chat it does not result in an exception. It fails silently.
Except if you hit the send limit, then you get a `@msg-id=msg_duplicate :tmi.twitch.tv NOTICE #channel :Your message was not sent because it is identical to the previous one you sent, less than 30 seconds ago.` message.

**Comment by JoshuaSkelly** [comment]
I think removing the channel arg from the Observer is a good idea.

I'm not sure about trying to track which channels you are connected to. This might be better left to the developer consuming our API. 

I've noticed that once requesting the membership capability, I no longer receive :End of /NAMES list.

**Comment by PythooonUser** [comment]
But receiving this token is the only check we can perform for a successful join to a chat.
So I guess this enhancement is in vain.
