### ISSUE TITLE
Improvement of class TwitchChatEvent

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#11]
Currently the class TwitchChatEvent has a type and a command.
The type is always "TWITCHCHATEVENT".

In [lunch-break-rl/player.py#L31](https://github.com/JoshuaSkelly/lunch-break-rl/blob/master/player.py#L31) there is no check for the command being "PRIVMSG".

In [lunch-break-rl/twitchchatmanager.py#L14](https://github.com/JoshuaSkelly/lunch-break-rl/blob/master/twitchchatmanager.py#L14) there is this check.

Maybe we create three subclasses that inherit from TwitchChatEvent, namely TwitchChatMessageEvent, TwitchChatJoinEvent and TwitchChatLeaveEvent. This way, we only need to make one check whether we are dealing with the correct event type, instead of first checking if its a TwitchChatEvent and then which type it is.

Because it seems that also checking for the right command value can be easily forgotten. Or am I mistaken? What do you think?

This should only be a quality of life update.

**Comment by JoshuaSkelly** [comment]
I agree that the current implementation is a bit clunky. Instead of subclassing, how about changing the Event structure a bit? My suggestion is to differentiate on the type:

```python
    def __init__(self, channel=None, command=None, message=''):
        event_types = {'JOIN': 'TWITCHCHATJOIN', 'PART': 'TWITCHCHATLEAVE', 'PRIVMSG': 'TWITCHCHATMESSAGE'}
        self.type = 'TWITCHCHATUNKNOWN'

        if command in event_types:
            self.type = event_types[command]

        self.channel = channel
        self.command = command
        self.message = message
```

**Comment by PythooonUser** [comment]
Okay.
Isn't the information redundant given by self.command and self.type?
I know, that we need the type argument because that is a requirement `tdl` gives us on a custom event class.
So I personally would check for the type, not the command in my own script.

**Comment by JoshuaSkelly** [comment]
Sort of. The command attribute is used by dumps() to serialize the message. The type attribute is to be used to handle the event.

Most Python event frameworks use the type attribute (both Pygame and tdl do) and I'm trying follow the established practices.

Perhaps we should rename self.command to self._command?

**Comment by PythooonUser** [comment]
Yeah, maybe the rename could do it. For dumps() the command information is also stored in the dictionary keys.

**Comment by JoshuaSkelly** [comment]
I'm not sure what you mean about:

> Yeah, maybe the rename could do it. For dumps() the command information is also stored in the dictionary keys.

**Comment by PythooonUser** [comment]
```python
if command in event_types:
            self.type = event_types[command]
```

**Comment by JoshuaSkelly** [comment]
That is a locally scoped variable. It is just to help select an appropriate type.

**Comment by PythooonUser** [comment]
Ah no, I was mistaken in thinking that the dictionary key could be easily deduced from the value, which is not an intended feature of a dictionary. Obviously^^

**Comment by JoshuaSkelly** [comment]
Like:

```python
command = {'TWITCHCHATMESSAGE': 'PRIVMSG', 'TWITCHCHATJOIN': 'JOIN', 'TWITCHCHATLEAVE': 'PART'}[self.type]
```

?

**Comment by PythooonUser** [comment]
Yes, like so.

**Comment by PythooonUser** [comment]
I withdraw from my previous statement.

**Comment by JoshuaSkelly** [comment]
Right now I'm inclined to take the simpler solution which is to rename the command attribute to imply it isn't meant to be used as part of the API.

**Comment by PythooonUser** [comment]
Yes, that is a good suggestion.
