### ISSUE TITLE
JOIN and PART Events Are Only Sent for Observer

### ISSUE THREAD

**Issue by JoshuaSkelly** [JoshuaSkelly/twitch-observer#12]
Currently we only receive a JOIN event we the Observer joins a channel, and not when other viewers join chat. To get these messages we need to request the Membership Twitch-specific IRC capabilities.

Will be addressed by #14

**Comment by PythooonUser** [comment]
Yes. During some tests yesterday I found that out as well.

**Comment by PythooonUser** [comment]
JOIN and LEAVE events now get properly propagated. This issue will be closed when #16 gets closed.

**Comment by PythooonUser** [comment]
Fixed with 23b0e03.
