### ISSUE TITLE
Twitch IRC Capability: Commands

### ISSUE THREAD

**Issue by JoshuaSkelly** [JoshuaSkelly/twitch-observer#16]
# Overview

The Twitch commands capability grants several new messages. I've read that requesting this capability will also all the receipt of whispers. This needs to be confirmed.

https://dev.twitch.tv/docs/v5/guides/irc/#twitch-irc-capability-commands

# Changes

New Messages:
- CLEARCHAT
- HOSTTARGET
- NOTICE
- RECONNECT
- ROOMSTATE
- USERNOTICE
- USERSTATE
- WHISPER

**Comment by JoshuaSkelly** [comment]
@PythooonUser would you be able to take a look at this?

**Comment by PythooonUser** [comment]
Yes, I try.

**Comment by JoshuaSkelly** [comment]
@PythooonUser Question: is #15 a prerequisite for this?

**Comment by PythooonUser** [comment]
This could be a prerequisite for the NOTICE command only, which takes a msg_id param.

**Comment by JoshuaSkelly** [comment]
Hmm. Does it still send it without requesting tags?

**Comment by PythooonUser** [comment]
The WHISPER command can be received. In chat use `/w nickname message`.

**Comment by PythooonUser** [comment]
The WHISPER command needs to have its own regex I think. The syntax for PythooonUser sending PythooonChatBot a whisper is:
`:pythooonuser!pythooonuser@pythooonuser.tmi.twitch.tv WHISPER pythooonchatbot :hello`.
So we can use the nickname we want to whisper to as the channel name without `#` as in the PRIVMSG regex.

**Comment by PythooonUser** [comment]
Is there something left here?
As far as I was able to test it, /ban and /clear issue a CLEARCHAT, but /unban does not.
Also I was not able to test the RECONNECT event since I believe it is issued by the server itself.

**Comment by PythooonUser** [comment]
If there is a message for a subscription with Twitch Prime, the PRIVMSG regex returns an error.

**Comment by JoshuaSkelly** [comment]
I will create an issue to improve how we use regular expressions to parse command parameters.

**Comment by JoshuaSkelly** [comment]
I think we are very close. I have some time this morning to review your changes.
