### ISSUE TITLE
Improve handling of emotes in messages

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#20]
## Overview
Some emotes in chat messages result in a charmap error when displayed in the console.

**Comment by PythooonUser** [comment]
Maybe we leave that to the developer.

**Comment by JoshuaSkelly** [comment]
So the error only occurs when printing the character to the console?

**Comment by PythooonUser** [comment]
I believe so. Could be possible that it works on Ubuntu. The Windows console isn't good at handling UTF-8, I believe.

**Comment by PythooonUser** [comment]
Most emotes have simple ASCII names that get parsed by Twitch. Some are not.

**Comment by JoshuaSkelly** [comment]
Understood. I'm sure the Linux and MacOS terminals do the correct thing. I say we leave this up to the developer to correctly handle this, if it is something they want to do.
