### ISSUE TITLE
Flat styled Badges in README.md

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#21]
## Summary
How about changing the layout of the badges in the README.md to use a flat style? This would better integrate with the flat styled header image.

[![License: GPL v3](https://img.shields.io/badge/license-MIT-blue.svg?style=flat-square)](./LICENSE) [![Python 2](https://img.shields.io/badge/python-2-blue.svg?style=flat-square)]() [![Python 3](https://img.shields.io/badge/python-3-blue.svg?style=flat-square)]()

**Comment by JoshuaSkelly** [comment]
I agree!

**Comment by JoshuaSkelly** [comment]
Fixes by 96508b946fed88249b7d0f24a29f65e4e7000925
