### ISSUE TITLE
Removing _channel attribute of TwitchChatObserver

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#22]
## Summary
I propose to remove the `_channel` attribute of the `TwitchChatObserver`, because we do not track the current channels the user has joined to and almost every `_send_message` wrapper takes a channel parameter (except `send_whisper` which operates on the user directly).

This means that we have to remove the initial join to a channel from the `start` method and let the user join after instantiating the observer.

This change has to be mentioned in the README.md examples as well.

**Comment by JoshuaSkelly** [comment]
This is a good clean up.
