### ISSUE TITLE
Add support for unsubscribing from observer

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#26]
## Summary
We should add support for unsubsribing a former subscribed method from the TwitchChatObserver. As I was working on #22 (PR #25) I noticed that the first example in the README did some unneccessary stop method calling. This was okay in the past, but @JoshuaSkelly changed the example to print a message to the channel afterwards which needs a working observer connection. This gets destroyed by the stop call.

I circumvented this issue by starting a new observer session, but this is surely not the best way to do it.

I propose to therefor simply be able to unsubscribe a method from the observer, so there is no need to stop and start the observer again.

(Furthermore the call to leave_channel is not really necessary)

### Example from README
```python
import time
from twitchobserver import Observer

votes = {}

def handle_event(event):
    if event.type != 'TWITCHCHATPRIVMSG':
        return
        
    if event.message[0:2].upper() == '!Y':
        votes[event.nickname] = 1
        
    elif event.message[0:2].upper() == '!N':
        votes[event.nickname] = -1
        

observer = Observer('Nick', 'oauth:abcdefghijklmnopqrstuvwxyz0123')
observer.subscribe(handle_event)

observer.send_message('Voting has started!', 'channel')

observer.start()
observer.join_channel('channel')
time.sleep(60)
observer.leave_channel('channel')
observer.stop()

observer = Observer('Nick', 'oauth:abcdefghijklmnopqrstuvwxyz0123')
observer.start()
observer.join_channel('channel')
observer.send_message('Voting is over!', 'channel')

time.sleep(2)
tally = sum(votes.values())

if tally > 0:
    observer.send_message('The yeas have it!', 'channel')

elif tally < 0:
    observer.send_message('The nays have it!', 'channel')

else:
    observer.send_message('Its a draw!', 'channel')

observer.leave_channel('channel')
observer.stop()
```

## Implementation
Am I correct in suggesting just to destroy the method reference in the list of subscribers `_subscribers`? Or do we have to wait for any worker thread to finish the notifications in order to not get a reference exception?

**Comment by JoshuaSkelly** [comment]
I agree that an unsubscribe method would be useful.

My example is very basic and more illustrative than useful in actual production.

**Comment by PythooonUser** [comment]
Adding the unsubscribe method will make it useful.
