### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#27]
## Summary
I noticed that we use the terms *user* and *nickname*, *aouth token* and *password*, as well as *channel* and *chat* interchangeable.

Should we match those? Which ones do you prefer?

I get that *aouth* needs to be written in same cases since that is the offical name in the docs, but for us it just can be the password.

**Comment by JoshuaSkelly** [comment]
Can you provide examples? I might be blind to what you are referring to.

**Comment by PythooonUser** [comment]
Well, for starters in TwitchChatEvent:
- It is called Twitch*Chat*Event
- It takes the attribute *channel*

Events, e.g. are called *USER*NOTICE. The TwitchChatObserver takes in a *nickname*. *ban_user* and *unban_user* call it *user*.

Also in the README, there we talk about the *nickname*.

Do you think this is too detailed?

**Comment by JoshuaSkelly** [comment]
I think of chat as the activity and channel as the location where chat occurs. How do you think of it?

I think of users having nicknames. For example ```ban_user()``` implies you are banning a person. I would read ```ban_nickname()``` as forbidding the name and not the person.

**Comment by PythooonUser** [comment]
Oh, that is a very good thought. I like it. Okay then.
