### ISSUE TITLE
Check for socket error breaks Python3 support

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#3]
## Summary
Adding the socket error check in [twitchobserver.py#L190](https://github.com/JoshuaSkelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L190) breaks the Python3 support for me with
```
    except socket.error, e:
                       ^
SyntaxError: invalid syntax
```

## Proposed Change
Instead of `except socket.error, e:` use `except socket.error as e:`, which works fine for both Python2 and Python3.

**Comment by JoshuaSkelly** [comment]
Fixed with: 33e53da701ef02bcac8dc483147f75c50c776ac2
