### ISSUE TITLE
Update Version Number

### ISSUE THREAD

**Issue by JoshuaSkelly** [JoshuaSkelly/twitch-observer#30]
## Overview

We've made significant improvements and I think that deserves a version bump! 🍺 

Since we've completed three feature level user stories, I propose version ```0.4.0```

Thoughts?

**Comment by JoshuaSkelly** [comment]
Or should we wait until #15 is completed?

**Comment by PythooonUser** [comment]
Then we can raise it again. So it's up-to-date.

**Comment by PythooonUser** [comment]
Updated with  e1a2312

**Comment by PythooonUser** [comment]
Or do we consider it `1.0` after #13?

**Comment by JoshuaSkelly** [comment]
Ha. What do we consider ```1.0.0``` ?

**Comment by PythooonUser** [comment]
The twitch-observer. Are there any features you are missing? (unit tests?^^)

**Comment by PythooonUser** [comment]
Information on followers or subscribers of a channel are not accessible with IRC, correct?

**Comment by JoshuaSkelly** [comment]
I'm working on improving our unit tests.

User information is not available via IRC. It may available through the Twitch API, but I'm not sure if that is within this projects scope or not.

**Comment by JoshuaSkelly** [comment]
Closing this as it is wandering off topic.
