### ISSUE TITLE
Adding colored PRIVMSG

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#34]
## Summary
The PRIVMSG event also supports colored messages to be send by preceeding the message with the token `/me`.

**Comment by JoshuaSkelly** [comment]
Yeah. I saw we don't do anything for the time being. If people actually use this and request it, then we can implement it.

**Comment by PythooonUser** [comment]
Okay. Then I close this issue but leave the branch for future reference.
