### ISSUE TITLE
Add PyPI Support

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#36]
## Summary
Do we want to put `twitch-observer` onto PyPI when we are hitting `1.0.0`?

**Comment by JoshuaSkelly** [comment]
I think the sooner the better. The project is at a point where it is very usable. I would only put off publishing if:
1. We are intending to make breaking API changes
2. Rename the project

**Comment by JoshuaSkelly** [comment]
Additionally I've registered for PyPi and I think I can publish? Do you know of any documentation on this process?

**Comment by PythooonUser** [comment]
This is what the offical documentation says:
https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

I don't think we will introduce any API breaking changes or rename it (as we discussed that already). So I'm okay with that.

**Comment by PythooonUser** [comment]
You might need to update the `__init__.py` or the `setup.py` though, as the tests might not be included?

**Comment by JoshuaSkelly** [comment]
The tests should not be included. We should only publish the production artifacts.

**Comment by PythooonUser** [comment]
You created a PyPI Account for that?

**Comment by JoshuaSkelly** [comment]
It's up!
https://pypi.python.org/pypi/twitchobserver

**Comment by PythooonUser** [comment]
And it works!
