### ISSUE TITLE
TravisCI Support

### ISSUE THREAD

**Issue by JoshuaSkelly** [JoshuaSkelly/twitch-observer#37]
## Overview

TravisCI is a continuous integration service that is free for open source projects. It automatically runs our tests when a PR is submitted. Ideally it would run the tests on both Python 2 and 3.

https://travis-ci.org/

**Comment by PythooonUser** [comment]
Ah, I read about that briefly. So it integrates with GitHub and tells us if a PR produces some issues? Very good idea.
