### ISSUE TITLE
Setup.py long_description

### ISSUE THREAD

**Issue by JoshuaSkelly** [JoshuaSkelly/twitch-observer#38]
## Overview

Most Python packages directly include their repo's README as the long description for PyPI. I am concerned that our README is too long for this. Perhaps we should have a more concise version for PyPI?

**Comment by JoshuaSkelly** [comment]
Might be related to #39

**Comment by PythooonUser** [comment]
Yes, I also think that the whole README is too much text.
Do you want to add to the long description actual code listings? Or do we only want to include the features list of the README as the long description?

**Comment by PythooonUser** [comment]
For the long description I would suggest:
```
Turn Twitch chatter into Python events.

Features
    Pure Python: No extra dependencies. Just plain and simple Python.
    Small API: With three classes and twelve methods, you can learn it over a coffee break.
    Event Based: Makes writing apps easy and straightforward.
    Context Manager: Further simplifies working with observers.
```

**Comment by JoshuaSkelly** [comment]
I've used an abbreviated version of our README.md. I tried using pypandoc to convert it dynamically, but without much luck. For the time I've just hard coded the description.
