### ISSUE TITLE
Sphinx Documentation

### ISSUE THREAD

**Issue by JoshuaSkelly** [JoshuaSkelly/twitch-observer#39]
## Overview

We really should have documentation for our project and Sphinx seems the way to go.

http://www.sphinx-doc.org/en/stable/

**Comment by PythooonUser** [comment]
I could have a look at that, if you like. It primarily means to convert the doc strings in a usable form, I guess.

**Comment by JoshuaSkelly** [comment]
Sure! Go ahead and look into this. I've  never dealt with it before so excited to see how it works.

**Comment by PythooonUser** [comment]
I tried to include the README.md in the documentation, but apparently I couln't get it to work.

**Comment by PythooonUser** [comment]
Removed the broken flavoured markdown support with 67e792c4f5bd5f478f4e52128f3aef91dcac6008.

**Comment by JoshuaSkelly** [comment]
Answers:
1. I don't think so.
2. I think breaking content into several sections makes it more accessible.
3. Perhaps? I think the goal of this feature is to have nice API documentation.

**Comment by JoshuaSkelly** [comment]
I've created a ReadtheDocs.org account and hooked up the repo! 😄

**Comment by PythooonUser** [comment]
Does that mean we have to reference the index.rst and then it's fine?

**Comment by JoshuaSkelly** [comment]
Yeah. I think I just point readthedocs.org to our index.rst and the rest is magic.

**Comment by JoshuaSkelly** [comment]
Also looks like you have the use_color change in your documentation branch? Should remove that.

**Comment by PythooonUser** [comment]
Upsi. Apparently I didn't clean my repo properly when switching branches.

**Comment by PythooonUser** [comment]
Is there something else you want to add to the documentation? I guess I'm finished.
