### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#40]
## Summary
Do we need a requirements.txt included in the repo? For our project it will be empty, but maybe it adds to the maturity of the repo?

**Comment by PythooonUser** [comment]
There might be two packages that need to be installed for the Sphinx documentation (if it works):
- recommonmark
- sphinx_rtd_theme

But I don't know if this needs to be considered here.

**Comment by JoshuaSkelly** [comment]
For our project, no. We have no dependencies and it doesn't make sense to have an empty requirements.txt

Those are development dependencies and not runtime. There is a target in the makefile to install development dependencies.

**Comment by PythooonUser** [comment]
Alright. Makes sense. Thanks :)
