### ISSUE TITLE
Travis CI Badge not working for documentation

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#44]
## Summary
The Travis CI Badge on top of the documentation links to the same URL than the README Badge does, but instead of showing build:passing it remains at build:unkwown.

**Comment by JoshuaSkelly** [comment]
I do not think we need the badges in the documentation. The goal of the documentation is to cleanly and concisely document the API. The README should indicate the status of the code and a quick overview.

**Comment by PythooonUser** [comment]
Makes sense!

**Comment by PythooonUser** [comment]
Fixed with 6112fbce70510a4c872867b94b3349c0af2227f9.
