### ISSUE TITLE
The Chat Moderation Update

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#48]
## Summary
I felt like adding these methods since we have some moderation commands built in but not all of them.

Currently available:
- list moderators
- clear chat history
- ban user
- unban user

Adding:
- change color
- add moderator
- remove moderator
- ignore user
- unignore user
- timout user
- set slow mode
- unset slow mode
- set subscriber mode
- unset subscriber mode
- set r9k mode
- unset r9k mode
- set followers mode
- unset followers mode
- set emoteonly mode
- unset emoteonly mode

## Questions
**QUESTION**: There are also commands for playing commercials, hosting and unhosting other channels. I do not feel these to be directly related to the chat. Do we want to add them anyways or not?

**QUESTION**: Are there any unit tests I can add for those new methods? They are just wrappers for the `TwitchObserver.send_message` method so I'm not sure how to deal with it. Having a test for `send_message` is sufficient?

**Comment by PythooonUser** [comment]
What about those questions @JoshuaSkelly?

**Comment by JoshuaSkelly** [comment]
I think for the time we can leave out commercials and hosting.

I don't think we need any tests for this. As you said, the underlying method is tested. As long as you've manually tested the new commands, I'm happy.

**Comment by PythooonUser** [comment]
I did. Hopefully I did not screw it up :D
