### ISSUE TITLE
Support for advanced Twitch API stuff

### ISSUE THREAD

**Issue by PythooonUser** [joshuaskelly/twitch-observer#52]
## Summary
We should add some features of the Twitch API that are (in)directly related to chat.
Those include:

- [x] check for a user to be a follower
- [x] check for a user to be a subscriber (is this already shown in the tags attribute of an event? Needs verification to be working. Requires an application ID)

Those information are currently not fetched by the IRC stuff.

**Comment by PythooonUser** [comment]
What do you think @joshuaskelly? Is this something worth implementing?
If so, what do you think about the current implementation in features/advanced-twitch-api-support?

**Comment by PythooonUser** [comment]
I am aware of the fact, that `urllib.request` is not available in Python2, as our buddy Travis points out.

**Comment by joshuaskelly** [comment]
I think that is getting outside of the scope for twitchobserver. :worried:

I'm fairly confident there exist Python API's to handle this.

**Comment by PythooonUser** [comment]
Yeah, I guess your're right. Besides that, one can check for a user to be a subscriber by looking at the tags component.
For followers one can keep a seperated list.
