### ISSUE TITLE
Flask-like decorator for handling events / commands

### ISSUE THREAD

**Issue by Senpos** [joshuaskelly/twitch-observer#56]
Hi,

It would be great to see event-handling system using decorators just like in [pyTelegramBotAPI](https://github.com/eternnoir/pyTelegramBotAPI#message-handlers) or Flask (routes).

Anyway, thank you for the library, I've found it to be extremely easy to use.

**Comment by joshuaskelly** [comment]
That is a good suggestion and should be straight forward to add.

@PythooonUser What are you thoughts?

@Senpos If you are making interesting stuff, please share! :)

**Comment by PythooonUser** [comment]
Hey all,

I'm very glad you are enjoying the package and find it useful! 🎉

I'm on the same page as @joshuaskelly with regards to the implementation of decorators.

My question is about specific use cases you have in mind.  Could you provide me with an example? That would be really helpful.

Thanks!

**Comment by joshuaskelly** [comment]
@PythooonUser I think that use case looks correct. Would we want to allow multiple command aliases?
```python
def on_command(*aliases):
```
Which then could be called:
```python
@observer.on_command('g', 'game')
def handle_on_command(event):
    print(event.message)
```
Or is this overkill?

**Comment by Senpos** [comment]
@PythooonUser 

Yes, you've got the idea pretty clear.

Let's say, we have enum with events:
```python
class ChatEventTypes(Enum):
    JOIN = "JOIN"
    LEAVE = "PART"
    MESSAGE = "PRIVMSG"
    MODE = "MODE"
    CLEARCHAT = "CLEARCHAT"
    HOSTTARGET = "HOSTTARGET"
    NOTICE = "NOTICE"
    RECONNECT = "RECONNECT"
    ROOMSTATE = "ROOMSTATE"
    USERNOTICE = "USERNOTICE"
    USERSTATE = "USERSTATE"
    WHISPER = "WHISPER"
    COMMAND = "COMMAND"
```

So, it could be cool to have decorator like this:
```python

@observer.on_event(ChatEventTypes.CLEARCHAT):
def clearchat_handler(event):
    pass
```

Also, it is handy to have shortcuts for most used things, like `COMMAND`, which will internally add command listener, just like example above: `@observer.on_event(ChatEventTypes.COMMAND)`

**Comment by Senpos** [comment]
@joshuaskelly 
Yeah, aliasing is also very common thing to do, imagine if we want to share our social links with both `!social` and `!me`. Especially, it is very important for multilingual chats, where you want to add a command for both your native language and English.

**Comment by PythooonUser** [comment]
@joshuaskelly Multiple commands can be used for aliasing, yes. What @Senpos suggests sounds pretty reasonable.

@Senpos I understand. For your information: There are already enums available, e.g. `ChatEventType` or `ChatColor`.

**Comment by PythooonUser** [comment]
@joshuaskelly If it's okay, I look into it. If time permits :) I develop on a new branch.

**Comment by Senpos** [comment]
@PythooonUser 

> There are already enums available, e.g. ChatEventType or ChatColor.

Yes, I know, that's where I found them. I have just modified it a bit and was gonna create a new issue with a proposal. Stay tuned. 😋

**Comment by PythooonUser** [comment]
I already figured :D Please, do so!

**Comment by PythooonUser** [comment]
It works as follows:

```python
import time
from twitchobserver import Observer, ChatEventType

observer = Observer('nickname', 'oauth:')

@observer.on_event(ChatEventType.TWITCHCHATMESSAGE)
def handle_join_event(event):
    print(event.message)

observer.subscribe(handle_join_event)

observer.start()
observer.join_channel("channel")

time.sleep(10)

observer.leave_channel("channel")
observer.stop()
```

**Comment by joshuaskelly** [comment]
I think the subscribe call can be pushed inside of the decorator?

**Comment by PythooonUser** [comment]
And also this:
```python
@observer.on_event(ChatEventType.TWITCHCHATMESSAGE)
@observer.on_command("social")
def handle_social_event(event):
    observer.send_message("Social is ...", "channel")

observer.subscribe(handle_social_event)
```

**Comment by PythooonUser** [comment]
> I think the subscribe call can be pushed inside of the decorator?
I try it^^

**Comment by joshuaskelly** [comment]
Let's just focus on `@on_event` for now.

**Comment by PythooonUser** [comment]
I just wanted to try it out
