### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/twitch-observer#6]
Ideas for the project name:
- twitch observer
- twitch listener
- twitch monitor
- twitch chat manager
- twitch chat controller
- twitch controller
- twitch manager
- twitch chat supervisor
- twitch chat companion
- twitch chat buddy

**Comment by JoshuaSkelly** [comment]
I'm thinking maybe a more creative name? For example:

gulp.js could have been named javascript-task-runner
yeoman could have been name project-scaffolding
etc.

Having said that, naming a project is **HARD**.

**Comment by PythooonUser** [comment]
Mmh, okay. I will keep thinking about it.

**Comment by JoshuaSkelly** [comment]
Perhaps I'm overthinking it? We probably don't need to rename the project?

**Comment by PythooonUser** [comment]
Well, primarily it *is* an observer to monitor the chat and return those messages as events in Python.

**Comment by JoshuaSkelly** [comment]
Cool. I'll close the issue.
