### ISSUE TITLE
Support for Stream Markers

### ISSUE THREAD

**Issue by PythooonUser** [joshuaskelly/twitch-observer#60]
## Summary
There is a new feature on Twitch, Stream Markers. See [help.twitch.tv](https://help.twitch.tv/customer/portal/articles/2946368-stream-markers) for an overview.

The Marker can be set via chat/command `/marker` which we could start supporting.

Thoughts @joshuaskelly?

**Comment by joshuaskelly** [comment]
Lets do it! :)
