### ISSUE TITLE
Potential typo ("sever" -> "server")

### ISSUE THREAD

**Issue by Senpos** [joshuaskelly/twitch-observer#63]
* [_**sever**_message_re](https://github.com/joshuaskelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L69)
* [# Handle **sever** messages
](https://github.com/joshuaskelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L514)
* [match = _**sever**_message_re.match(message)](https://github.com/joshuaskelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L515)

All of these are typos, I guess.

**Comment by PythooonUser** [comment]
Yep. Those are typos. Do you want to create a PR for that?

**Comment by Senpos** [comment]
@PythooonUser 
Yes, sure!

**Comment by PythooonUser** [comment]
Yes, those are typos. Do you want to create a PR for that?

**Comment by Senpos** [comment]
@PythooonUser 
I'd also like to ask about using [`self.nickname` atribute here](https://github.com/joshuaskelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L65), as well as in [`TwitchChatEvent` docstrings](https://github.com/joshuaskelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L20), is this a mistake? I don't see it in `__init__`.  Actually, I don't see it anywhere in the project. 

Should I fix it at the same PR and name it like "Fix typos & unused nickname attr"?
Give me some recommendations please.

**Comment by PythooonUser** [comment]
No, this is one of the most important variables! :D
Look at [_process_server_messages](https://github.com/joshuaskelly/twitch-observer/blob/8358d6ebcb3f849681d50753c951114433871f3e/twitchobserver/twitchobserver.py#L519). Here the `nickname` is set. This variable is send for JOIN, PART and MSG events to identify the user that triggered it.
We had a discussion about the naming once. We stayed with the Twitch way of naming things.

**Comment by Senpos** [comment]
@PythooonUser 
Oops!
I searched for `self.nickname` rather than `nickname`! Sorry.

**Comment by PythooonUser** [comment]
No problem. So I think fixing the typos in your PR is sufficient for now ;)
