### ISSUE TITLE
Simplify Naming Conventions

### ISSUE THREAD

**Issue by joshuaskelly** [joshuaskelly/twitch-observer#65]
## Summary
Many of the classes and attributes have redundant info and should be simplified.
e.g.
> TwitchChatObserver -> Observer

### Classes
| Current | Proposed |
|----------|------------|
| BadTwitchChatEvent | BadEvent |
| TwitchChatEvent | Event |
| TwitchChatObserver | Observer |
| TwitchChatColor | Color |

### Chat Event Types
| Current | Proposed |
|----------|------------|
| TWITCHCHATJOIN | JOIN |
| TWITCHCHATLEAVE | LEAVE |
| TWITCHCHATMESSAGE | MESSAGE |
| TWITCHCHATMODE | MODE |
| TWITCHCHATCLEARCHAT | CLEARCHAT |
| TWITCHCHATHOSTTARGET | HOSTTARGET |
| TWITCHCHATNOTICE | NOTICE |
| TWITCHCHATRECONNECT | RECONNECT |
| TWITCHCHATROOMSTATE | ROOMSTATE |
| TWITCHCHATUSERNOTICE | USERNOTICE |
| TWITCHCHATUSERSTATE | USERSTATE |
| TWITCHCHATWHISPER | WHISPER |
| TWITCHCHATCOMMAND | COMMAND |

**Comment by joshuaskelly** [comment]
If I missed any names or if there is a better naming scheme, let me know.

**Comment by PythooonUser** [comment]
**Question:** What about the strings of the ChatEventTypes? Do they stay the same?

**Question:** Am I right that the aliases defined in the `__init__.py` file aren't required any more?

**Comment by joshuaskelly** [comment]
> What about the strings of the ChatEventTypes? Do they stay the same?

I think we should change those? Since we are already making big breaking changes.

> Am I right that the aliases defined in the __init__.py file aren't required any more?

I'd say yes, we can remove those.

**Comment by PythooonUser** [comment]
> I think we should change those?

What about naming conflicts with e.g. `tdl`, `pygame` or custom event types?

**Comment by joshuaskelly** [comment]
Good point. Maybe we can wait before changing those? I'm not quite sure yet how I feel about that change.

**Comment by PythooonUser** [comment]
> I'm not quite sure yet how I feel about that change.

About the whole change? Please, speak up if you have any concerns!

**Comment by PythooonUser** [comment]
Anyways, I'm willing to work on this issue.

**Comment by joshuaskelly** [comment]
Go for it! 😄
