### ISSUE TITLE
Regarding Versioning

### ISSUE THREAD

**Issue by PythooonUser** [joshuaskelly/twitch-observer#68]
## Summary
As of recent questions and maybe a slight confusion on my end (:P) I want to ask a question regarding the project versioning.

@joshuaskelly already mentioned we use semantic versioning, i.e. `[major][minor][patch]`.

My question is more of an organizational nature. **When do we increase the version?**
- After each PR?
- After each group of similar PRs?
- After a specific time frame of development?

Also, should increasing the version be part of the PR? Or done after that seperatly?

Personally, I would favour option two and having the version bumping done afterwards.

Thoughts?

**Comment by PythooonUser** [comment]
I created a `v0.10.0` milestone.

**Comment by Senpos** [comment]
>After a specific time frame of development?

I'd go with it.

Merge PRs and then add new commit with version bump, when things are ready for new release.

**Comment by joshuaskelly** [comment]
We should bump the version number before we publish. 

Thanks for creating a milestone @PythooonUser !

**Comment by PythooonUser** [comment]
Alright! Milestone it is. Closing.
