### ISSUE TITLE
Create "develop" branch

### ISSUE THREAD

**Issue by Senpos** [joshuaskelly/twitch-observer#70]
Merging all the latest stuff to master may hurt end-users, so it might be a good idea to create develop branch to store there all the bleeding-edge features.

**Comment by PythooonUser** [comment]
Generally this is a good idea, but I need to ask if this is really necessary for a project of this scope?
We will have about 2-4 PRs for the next release and then development will go silent again I guess.
If users work with the PyPI provided package they only get the latest stable version. Only us developers will install twitchobserver using `pip install -e`.
Thoughts?

**Comment by joshuaskelly** [comment]
I agree that this is overkill for a project for this scope.
