### ISSUE TITLE
Question: Multiple channels command bot

### ISSUE THREAD

**Issue by Firerazer** [JoshuaSkelly/twitch-observer#76]
Hello,
I have a question: I am a twitch stream team administrator (and not a programmer) and I am looking for a bot to handle all team related commands to avoid streamers to all copy/paste the same command into their respective bot. 
Is your bot able to do this?

**Comment by PythooonUser** [comment]
Hey @Firerazer,

thank you for checking out our project!

If I'm not mistaken this should be possible by our bot (we do not have an example for this use-case in our wiki, though).

In principle you can create a bot and let it join multiple channels. What we do in the background is to send a simple `JOIN channel_name` event to the chat server.

Every event that our bot receives includes the channel name as a parameter.

I hope this helps,
let us know if you need further advice.

You can have a look at our wiki to get started.

@joshuaskelly I hope my information given above is correct? :D

**Comment by Firerazer** [comment]
Thanks, I will let know my server guys to take a look at your project so :)

**Comment by joshuaskelly** [comment]
@PythooonUser You are 💯 correct!

@Firerazer Rad! Feel free to submit issues/PRs. 👍
