### ISSUE TITLE
Improve TwitchChatObserver.subscribe()

### ISSUE THREAD

**Issue by JoshuaSkelly** [JoshuaSkelly/twitch-observer#8]
The inbound worker thread handles notifying subscribers. If a subscribed callback raises an Exception it will terminate the inbound worker thread. Currently we have no way of detecting this, and the TwitchChatObserver will be left in a bad state.

We should probably handle this in a more graceful manner.

**Comment by PythooonUser** [comment]
So how to do this? Catch the error in the inbound worker thread, print it to the user and go on?

**Comment by PythooonUser** [comment]
Maybe unsubscribe the callback?

**Comment by PythooonUser** [comment]
Or just print a RuntimeWarning?
